<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Exploring Relationships – Sociology of Water Management</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter7.html" rel="next">
<link href="./chapter5.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-70a47bd5681a7291082a5b9f83d58762.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="references.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter6.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Exploring Relationships</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Sociology of Water Management</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Watersheds and Their People</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Human Dimensions of Water</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">West MI Watersheds</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">From Data To Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing Survey Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter6.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Exploring Relationships</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Research Writing</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link active" data-scroll-target="#hypothesis-testing"><span class="header-section-number">6.1</span> Hypothesis Testing</a></li>
  <li><a href="#statistical-significance" id="toc-statistical-significance" class="nav-link" data-scroll-target="#statistical-significance"><span class="header-section-number">6.2</span> Statistical Significance</a></li>
  <li><a href="#measures-of-association" id="toc-measures-of-association" class="nav-link" data-scroll-target="#measures-of-association"><span class="header-section-number">6.3</span> Measures of Association</a>
  <ul class="collapse">
  <li><a href="#chi-square-test" id="toc-chi-square-test" class="nav-link" data-scroll-target="#chi-square-test"><span class="header-section-number">6.3.1</span> Chi-Square Test</a></li>
  <li><a href="#spearmans-rank-correlation" id="toc-spearmans-rank-correlation" class="nav-link" data-scroll-target="#spearmans-rank-correlation"><span class="header-section-number">6.3.2</span> Spearman’s Rank Correlation</a></li>
  </ul></li>
  <li><a href="#comparing-groups" id="toc-comparing-groups" class="nav-link" data-scroll-target="#comparing-groups"><span class="header-section-number">6.4</span> Comparing Groups</a>
  <ul class="collapse">
  <li><a href="#comparing-two-groups" id="toc-comparing-two-groups" class="nav-link" data-scroll-target="#comparing-two-groups"><span class="header-section-number">6.4.1</span> Comparing Two Groups</a></li>
  <li><a href="#comparing-three-or-more-groups" id="toc-comparing-three-or-more-groups" class="nav-link" data-scroll-target="#comparing-three-or-more-groups"><span class="header-section-number">6.4.2</span> Comparing Three or More Groups</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">6.5</span> Summary</a></li>
  <li><a href="#reflection-questions" id="toc-reflection-questions" class="nav-link" data-scroll-target="#reflection-questions"><span class="header-section-number">6.6</span> Reflection Questions</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">6.7</span> References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Exploring Relationships</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Learning Objectives</strong></p>
<ul>
<li>Formulate clear, testable hypotheses</li>
<li>Explain the logic of null hypothesis significance testing (NHST)</li>
<li>Select and apply appropriate measures of association</li>
<li>Interpret and communicate statistical results</li>
</ul>
<hr>
<p>Watershed research, like social science more broadly, is often concerned with relationships. We may wonder how environmental conditions, behaviors, or perceptions relate and whether they vary together in meaningful ways. Hypothesis testing provides a structured way to evaluate these questions using data.</p>
<p>In this chapter, we focus on identifying independent and dependent variables and thinking critically about what kinds of relationships might exist in a dataset. Understanding these foundational elements will help you choose the appropriate statistical tests to evaluate associations in your data, ensuring you have a clear framework for testing relationships in your data.</p>
<p>This chapter was adapted from <a href="https://pressbooks.ric.edu/socialdataanalysis/">Arthur and Clark (2021)</a>, a valuable source for further reading on hypothesis testing and measures of association.</p>
<section id="hypothesis-testing" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="hypothesis-testing"><span class="header-section-number">6.1</span> Hypothesis Testing</h2>
<p>A <abbr title="A statement making a prediction about a characteristic of a population." style="font-weight: bold; text-decoration: underline dotted; cursor: help;"> <em>hypothesis</em> </abbr> is a clear, testable statement about a relationship we expect to observe in the world. Hypotheses force us to be explicit about what we think is related to what, and in which direction that relationship operates.</p>
<p>Stating a hypothesis requires distinguishing between independent and dependent variables.</p>
<ul>
<li>The <strong>independent variable (IV)</strong> is the causal factor that drives a change in another (dependent) variable. This is also called the <strong>explanatory variable</strong>.</li>
<li>The <strong>dependent variable (DV)</strong> is the outcome variable that changes in response to the independent variable. This is also called the <strong>response variable</strong>.</li>
</ul>
<p>Hypotheses formalize expectations about how these variables relate at the population level. The <abbr title="A statement assuming that there is an absence of effect." style="font-weight: bold; text-decoration: underline dotted; cursor: help;"> <em>null hypothesis</em> </abbr> (<span class="math inline">\(H_0\)</span>) states that no relationship exists between variables. In contrast, the <abbr title="A statement assuming that an observed value differs from the null." style="font-weight: bold; text-decoration: underline dotted; cursor: help;"> <em>alternative hypothesis</em> </abbr> (<span class="math inline">\(H_1\)</span>) proposes that a relationship does exist.</p>
<p>For example:</p>
<ul>
<li><p><span class="math inline">\(H_0\)</span>: There is no relationship between the number of ice cream cones eaten in the past 12 months and belt size (all right!).</p></li>
<li><p><span class="math inline">\(H_1\)</span>: There is a positive relationship between the number of ice cream cones eaten in the past 12 months and belt size; as the number of ice cream cones eaten increases, so does belt size (bummer!).</p></li>
</ul>
<p>While decidedly on the silly side, this example illustrates that hypotheses are not conclusions; they are claims to be evaluated.</p>
</section>
<section id="statistical-significance" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="statistical-significance"><span class="header-section-number">6.2</span> Statistical Significance</h2>
<p>How do we know if two variables in our dataset are related in a statistically meaningful way?</p>
<p><abbr title="A method for evaluating evidence in a dataset by assessing how likely an observed result would be if the null hypothesis were true." style="font-weight: bold; text-decoration: underline dotted; cursor: help;"> <em>Null hypothesis significance testing,</em> </abbr> or NHST, is a method of testing for statistical significance by comparing observed data to what we would expect to see if there were no relationship between the variables or phenomena in question. NHST begins by assuming the null hypothesis is true. Evidence from the data is then used to determine whether this assumption should be rejected. This approach, while somewhat counterintuitive, means that we assume that differences or patterns occur due to chance unless strong evidence suggests otherwise. This keeps us searching for evidence that disconfirms our hypothesis, making it less likely that we will accept a conclusion that later turns out to be untrue.</p>
<p>The <abbr title="A value that indicates how likely an observed result could have occurred by chance under the null hypothesis." style="font-weight: bold; text-decoration: underline dotted; cursor: help;"> <em><span class="math inline">\(p\)</span>-value</em> </abbr> represents the probability of observing a test statistic as extreme as the one obtained <em>if the null hypothesis were correct.</em> Smaller <span class="math inline">\(p\)</span>-values indicate that the observed data are less consistent with the null hypothesis.</p>
<p>In practice, researchers select a significance level (commonly <span class="math inline">\(p &lt; 0.05\)</span>) that reflects how much risk they are willing to accept of mistakenly rejecting the null hypothesis. When the <span class="math inline">\(p\)</span>-value falls below this threshold, the result is considered statistically significant, and the null hypothesis is rejected.</p>
<p>A <span class="math inline">\(p\)</span>-value can be interpreted as the percent likelihood that the pattern we observed could have occurred by chance, assuming there is actually no relationship in the population. For example, a <span class="math inline">\(p\)</span>-value of 0.03 suggests that <em>if the null hypothesis were correct,</em> there is about a 3% chance of observing a result this extreme due to random variation alone. In other words, it is unlikely that chance alone (the null hypothesis) explains the observed result.</p>
<p>When the <span class="math inline">\(p\)</span>-value falls below the chosen significance level, we conclude that the observed pattern is sufficiently unlikely to be explained by chance variation and reject the null hypothesis. When the <span class="math inline">\(p\)</span>-value exceeds the threshold, the evidence is not strong enough to rule out chance as a possible explanation, and the null hypothesis is not rejected.</p>
<p>Feeling confused? Stop and watch this easy-to-follow explanation from the experts at Data Demystified:</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/DAkJhY2zQ3c?si=tt2lqwad6rAhu6Fp" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen="">
</iframe>
<p>Importantly, statistical significance does not imply that a relationship is large, important, or causal - only that it is unlikely to have occurred by chance, as assumed by the null hypothesis.</p>
</section>
<section id="measures-of-association" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="measures-of-association"><span class="header-section-number">6.3</span> Measures of Association</h2>
<p>Once a hypothesis is specified and uncertainty is acknowledged, we turn to measures of association to quantify relationships between variables. These measures provide a way to summarize how strongly variables are related and whether observed patterns are consistent with more than chance variation.</p>
<p>A <abbr title="A numerical summary of sample data used to evaluate a hypothesis." style="font-weight: bold; text-decoration: underline dotted; cursor: help;"> <em>test statistic</em> </abbr> is a numerical value calculated from sample data that summarizes evidence against the null hypothesis and is used to compute a <span class="math inline">\(p\)</span>-value. The test statistic reflects whether there is a consistent and robust association between variables.</p>
<p>There are different tests of statistical significance, and the technique you’ll use will depend on the characteristics of the variables you are examining.</p>
<section id="chi-square-test" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="chi-square-test"><span class="header-section-number">6.3.1</span> Chi-Square Test</h3>
<p>A <strong>Chi-Square</strong> (<span class="math inline">\(\chi^2\)</span>) test is a statistical test used to determine whether there is a statistically significant association between two categorical variables. It is commonly applied when variables consist of a small number of categories and can be summarized in a contingency table.</p>
<p>For example, we might ask: <em>Is property type related to how important fishing is to residents?</em></p>
<p>In this case, the hypotheses can be stated as:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Property type and the importance of fishing are statistically independent; owners of different property types are equally likely to consider fishing important.</li>
<li><span class="math inline">\(H_1\)</span>: Property type and the importance of fishing are not statistically independent; the importance of fishing varies across property types.</li>
</ul>
<p>Before computing the Chi-square statistic, it is useful to first examine how responses are distributed across categories. A <strong>contingency table</strong> (also called a cross-tabulation) summarizes this relationship by displaying the frequency of each combination of categories. Rows represent one variable, columns represent the other, and cells contain the number (and often percentage) of observations in each category combination. Because interpretation becomes more difficult as the number of categories increases, contingency tables are most effective when variables have relatively few categories (typically two or three).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstatix)  </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"demo_data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">MOSTIMPFISH_MISS =</span> <span class="fu">na_if</span>(MOSTIMPFISH, <span class="dv">9</span>),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">TYPE_FACTOR =</span> <span class="fu">factor</span>(TYPE,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Residential"</span>, <span class="st">"Small farm"</span>, <span class="st">"Large farm"</span>)),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">MOSTIMPFISH_FACTOR =</span> <span class="fu">factor</span>(MOSTIMPFISH_MISS,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>                              <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>                              <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Not important"</span>, <span class="st">"Important"</span>))</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(TYPE_FACTOR, MOSTIMPFISH_FACTOR)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>crosstab <span class="ot">&lt;-</span> data2 <span class="sc">%&gt;%</span>  </span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(TYPE_FACTOR, MOSTIMPFISH_FACTOR) <span class="sc">%&gt;%</span> </span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_totals</span>(<span class="at">where =</span> <span class="st">"col"</span>) <span class="sc">%&gt;%</span>   </span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_percentages</span>(<span class="at">denominator =</span> <span class="st">"row"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_pct_formatting</span>(<span class="at">digits =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span>  </span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adorn_ns</span>()  </span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>crosstab</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> TYPE_FACTOR Not important  Important        Total
 Residential    54.8% (86) 45.2% (71) 100.0% (157)
  Small farm    61.3% (57) 38.7% (36) 100.0%  (93)
  Large farm    56.5% (26) 43.5% (20) 100.0%  (46)</code></pre>
</div>
</div>
<p>In this example, the contingency table shows that:</p>
<ul>
<li>Among residential property owners, 54.8% reported that fishing is not an important activity, while 45.2% reported that it is important.</li>
<li>Among small farm owners, 61.3% reported that fishing is not an important activity, and 45.2% reported that it is important.</li>
<li>Among large farm owners, 56.5% reported that fishing is not important, and 43.5% reported that it is important.</li>
</ul>
<p>To formally evaluate whether these observed differences are larger than we would expect by chance alone, we use a Chi-square test of independence.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>chisq_result <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(<span class="fu">xtabs</span>(<span class="sc">~</span> TYPE_FACTOR <span class="sc">+</span> MOSTIMPFISH_FACTOR, <span class="at">data =</span> data2))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>chisq_result <span class="sc">%&gt;%</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">tidy</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(statistic, parameter, p.value) <span class="sc">%&gt;%</span> </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">chi_square =</span> statistic,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> parameter,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_value =</span> p.value</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  chi_square    df p_value
       &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
1       1.02     2   0.601</code></pre>
</div>
</div>
<p>The Chi-square test output indicates a test statistic of <span class="math inline">\(\chi^2 = 1.02\)</span> with 2 <abbr title="The number of independent comparisons being made in the table." style="font-weight: bold; text-decoration: underline dotted; cursor: help;"> <em>degrees of freedom</em> </abbr> and a <span class="math inline">\(p\)</span>-value of 0.60. This <span class="math inline">\(p\)</span>-value is well above the conventional significance threshold of 0.05, meaning that differences of this size would be fairly common if property type and the importance of fishing were truly unrelated in the population.</p>
<p>Because the <span class="math inline">\(p\)</span>-value exceeds the chosen significance level, we <em>fail to reject the null hypothesis.</em> In practical terms, this means that although the percentages differ somewhat across property types, the evidence is not strong enough to conclude that property type and the importance of fishing are associated beyond what might occur by chance.</p>
</section>
<section id="spearmans-rank-correlation" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="spearmans-rank-correlation"><span class="header-section-number">6.3.2</span> Spearman’s Rank Correlation</h3>
<p>While the Chi-square test is used to examine relationship between categorical variables, correlation coefficients are used to assess associations between variables measured on an ordinal or continuous scale. <strong>Spearman’s rho</strong> measures the direction and strength of the relationship between two variables by asking whether higher or lower values of one variable tend to be associated with higher or lower values of another. Instead of comparing exact numeric values, it compares the relative ordering of observations, which makes it appropriate for ordinal data.</p>
<p>For example, we might ask: <em>Is perceived severity of E. coli pollution related to education level?</em></p>
<p>This question can be framed using the following hypotheses:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: There is no association between perceptions of <em>E. coli</em> pollution and education level.</li>
<li><span class="math inline">\(H_1\)</span>: There is an association between perceptions of <em>E. coli</em> pollution and education level.</li>
</ul>
<p>The alternative hypothesis can be further specified by direction. A <strong>positive association</strong> would indicate that concern about <em>E. coli</em> pollution increases as education level increases, while a <strong>negative association</strong> would indicate that concern decreases as education level increases.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span>  </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">IMPECOLI_MISS =</span> <span class="fu">na_if</span>(IMPECOLI, <span class="dv">9</span>),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">EDUCATION_MISS =</span> <span class="fu">na_if</span>(EDUCATION, <span class="dv">9</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">drop_na</span>(IMPECOLI_MISS, EDUCATION_MISS)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>cor_test_result <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span>   </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor_test</span>(IMPECOLI_MISS, EDUCATION, <span class="at">method =</span> <span class="st">"spearman"</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>cor_test_result <span class="sc">%&gt;%</span> </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(cor, p) <span class="sc">%&gt;%</span> </span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">rho =</span> cor,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_value =</span> p</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
     rho p_value
   &lt;dbl&gt;   &lt;dbl&gt;
1 -0.099   0.179</code></pre>
</div>
</div>
<p>Spearman’s rho ranges from −1 to +1, with values closer to −1 or +1 indicating stronger associations and values near zero indicating weak or no association. As a general guideline:</p>
<ul>
<li><span class="math inline">\(|\rho| &lt; 0.3\)</span> indicates a weak association<br>
</li>
<li><span class="math inline">\(0.3 \le |\rho| &lt; 0.6\)</span> indicates a moderate association<br>
</li>
<li><span class="math inline">\(|\rho| \ge 0.6\)</span> indicates a strong association</li>
</ul>
<p>In this example, Spearman’s rho is −0.10, indicating a <em>very weak negative association</em> between education level and perceived severity of <em>E. coli</em> pollution. This suggests that respondents with higher levels of education report slightly lower concern about <em>E. coli</em> pollution, although the relationship is minimal in magnitude and explains very little variation in perceptions.</p>
<p>The associated <span class="math inline">\(p\)</span>-value is 0.18, which exceeds the conventional significance threshold of 0.05. This means that an association of this size would be fairly common if there were truly no relationship between education level and perceptions of <em>E. coli</em> pollution in the population. As a result, we <em>fail to reject the null hypothesis</em> and conclude that there is insufficient evidence to support a meaningful association beyond what might be expected by chance.</p>
</section>
</section>
<section id="comparing-groups" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="comparing-groups"><span class="header-section-number">6.4</span> Comparing Groups</h2>
<p>Comparing groups is a special case of relationship analysis in which the independent variable defines group membership. Rather than asking whether two variables vary together, we are asking whether distributions differ across groups.</p>
<p>When the outcome variable is ordinal - as many variables in the West MI Watersheds Database are - we use rank-based tests to compare groups.</p>
<section id="comparing-two-groups" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="comparing-two-groups"><span class="header-section-number">6.4.1</span> Comparing Two Groups</h3>
<p>The <strong>Mann-Whitney U</strong> statistic, (also reported as the <strong>W</strong> statistic in R), is used to compare the distribution of an ordinal outcome between two independent groups. Instead of comparing means (like a t-test), the Mann-Whitney U test evaluates whether values from one group tend to by systematically higher or lower than values from the other group.</p>
<p>For example, we might as: <em>Do perceptions of E. coli pollution differ between men and women?</em></p>
<p>This question can be framed using the following hypotheses:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The distributions of perceived <em>E. coli</em> pollution severity are the same for men and women.</li>
<li><span class="math inline">\(H_1\)</span>: The distributions of perceived <em>E. coli</em> pollution severity differ between men and women.</li>
</ul>
<p>The Mann-Whitney U test works by ranking all observations across both groups and comparing the sum of ranks for each group. If one group consistently has higher ranks than the other, this suggests a difference in distributions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>data3 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">IMPECOLI_MISS =</span> <span class="fu">na_if</span>(IMPECOLI, <span class="dv">9</span>),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">GENDER_FACTOR =</span> <span class="fu">factor</span>(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">na_if</span>(GENDER, <span class="dv">9</span>),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"Female"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(IMPECOLI_MISS, GENDER_FACTOR)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>w_result <span class="ot">&lt;-</span> data3 <span class="sc">%&gt;%</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wilcox_test</span>(IMPECOLI_MISS <span class="sc">~</span> GENDER_FACTOR, <span class="at">exact =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>w_result <span class="sc">%&gt;%</span> </span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">W =</span> <span class="fu">round</span>(statistic, <span class="dv">0</span>),</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_value =</span> <span class="fu">round</span>(p, <span class="dv">3</span>)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
      W p_value
  &lt;dbl&gt;   &lt;dbl&gt;
1  2935   0.026</code></pre>
</div>
</div>
<p>Because <strong>W</strong> is based on the sum of ranks, its possible values depend on how many observations are in each group. The maximum possible value of <strong>W</strong> is given by:</p>
<p><span class="math inline">\(W_{\max} = n_1 \times n_2\)</span>.</p>
<p>The smallest value occurs when all observations in one group receive lower ranks than those in the other group, and the largest value occurs when all observations in one group receive higher ranks. Values near the middle of this range indicate substantial overlap between group distributions, while values closer to the extremes indicate greater separation.</p>
<p>In this example, the Mann-Whitney U test produced a test statistic of <strong>W = 2935</strong> with an associated <span class="math inline">\(p\)</span>-value of 0.026. Because the <span class="math inline">\(p\)</span>-value is below the conventional significance threshold of 0.05, we reject the null hypothesis and conclude that perceptions of <em>E. coli</em> pollution severity differ between male and female respondents.</p>
<p>Examining the group medians helps clarify the direction of this difference.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>data3 <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(GENDER_FACTOR) <span class="sc">%&gt;%</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_impecoli =</span> <span class="fu">median</span>(IMPECOLI_MISS),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  GENDER_FACTOR     n median_impecoli
  &lt;fct&gt;         &lt;int&gt;           &lt;dbl&gt;
1 Male            112               2
2 Female           65               3</code></pre>
</div>
</div>
<p>The median perceived severity score is 2 for male respondents and 3 for female respondents, indicating that female respondents tend to report higher concern about <em>E. coli</em> pollution than male respondents. In terms of the Mann–Whitney test logic, this means that responses from female respondents tend to receive higher ranks than responses from male respondents.</p>
<p>Together, these results suggest a statistically significant difference in perceived <em>E. coli</em> pollution severity by gender. While the Mann–Whitney U test does not estimate the size of this difference in the original measurement units, it provides evidence that the distributions of concern are not the same across the two groups and that gender is associated with variation in perceived pollution severity.</p>
</section>
<section id="comparing-three-or-more-groups" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="comparing-three-or-more-groups"><span class="header-section-number">6.4.2</span> Comparing Three or More Groups</h3>
<p>When the independent variable defines three or more groups, the <strong>Kruskal-Wallis</strong> test extends the logic of the Mann-Whitney U test to multiple groups. Like the Mann–Whitney test, it relies on ranked data and compares distributions rather than means.</p>
<p>For example, we might ask: <em>Does the frequency of septic system pumping differ by property owner type?</em></p>
<p>The hypotheses can be stated as:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The distributions of septic system pumping frequency are the same across all property owner types.</li>
<li><span class="math inline">\(H_1\)</span>: At least one property owner group has a different distribution of septic system pumping frequency.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>kw_result <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kruskal_test</span>(SEPTICPUMP <span class="sc">~</span> TYPE) <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(statistic, df, p) <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">H =</span> <span class="fu">round</span>(statistic, <span class="dv">2</span>),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_value =</span> <span class="fu">round</span>(p, <span class="dv">3</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(H, df, p_value)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>kw_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
      H    df p_value
  &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
1   1.9     2   0.386</code></pre>
</div>
</div>
<p>In this example, the Kruskal-Wallis test was used to examine whether the septic system pumping frequency differs across property owner types (residential, small farm, and large farm).</p>
<p>The test produced an H statistic of 1.90 with 2 degrees of freedom and an associated <span class="math inline">\(p\)</span>-value of 0.386. Because this <span class="math inline">\(p\)</span>-value is well above the conventional significance threshold of 0.05, we fail to reject the null hypothesis. This indicates that the observed differences in septic pumping frequency across property owner types are not sufficiently large to rule out chance variation under the null hypothesis.</p>
<p>In practical terms, this result suggests that the distributions of septic system pumping frequency are broadly similar across residential, small farm, and large farm properties in this dataset. Although individual households may differ in how often they pump their systems, there is no statistical evidence that pumping frequency systematically varies by property type.</p>
<p>The Kruskal-Wallis test does not tell us which groups differ, only that at least one group differs. If we reject <span class="math inline">\(H_0\)</span>, we need to conduct <strong>Dunn’s post-hoc test</strong> to determine which group is not like the others. For the sake of demonstration, we will conduct post-hoc pairwise comparisons using our current example, but note that post-hoc tests are only necessary when the overall Kruskal-Wallis test is statistically significant because post-hoc tests are designed to identify which groups differ after an overall difference has been established.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>dunn_result <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span>  </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dunn_test</span>(SEPTICYEAR <span class="sc">~</span> TYPE, <span class="at">p.adjust.method =</span> <span class="st">"holm"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">group1 =</span> <span class="fu">recode</span>(group1, <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Residential"</span>, <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"Small farm"</span>, <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"Large farm"</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">group2 =</span> <span class="fu">recode</span>(group2, <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"Residential"</span>, <span class="st">"2"</span> <span class="ot">=</span> <span class="st">"Small farm"</span>, <span class="st">"3"</span> <span class="ot">=</span> <span class="st">"Large farm"</span>),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">significant =</span> <span class="fu">if_else</span>(p.adj <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(group1, group2, statistic, p.adj, significant) <span class="sc">%&gt;%</span> </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">comparison_1 =</span> group1,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">comparison_2 =</span> group2,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Z =</span> statistic,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_value_adj =</span> p.adj</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>dunn_result</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  comparison_1 comparison_2      Z p_value_adj significant
  &lt;chr&gt;        &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;      
1 Residential  Small farm    0.279      0.780  No         
2 Residential  Large farm   -2.40       0.0340 Yes        
3 Small farm   Large farm   -2.53       0.0340 Yes        </code></pre>
</div>
</div>
<p>Each row in the output represents a comparison between two groups, and the adjusted <span class="math inline">\(p\)</span>-values account for the increased risk of false positives that arises when conducting multiple tests.</p>
<p>In this example, comparisons involving large farm properties show statistically significant differences from both residential and small farm properties after adjustment. However, because the overall Kruskal-Wallis test was not statistically significant, these differences should be interpreted cautiously and should not be taken as strong evidence of systematic differences across property types.</p>
</section>
</section>
<section id="summary" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="summary"><span class="header-section-number">6.5</span> Summary</h2>
<p>In this chapter, we moved from describing individual variables to examining relationships between variables. We began by defining hypotheses as testable statements about expected relationships and emphasized the importance of clearly identifying independent and dependent variables before conducting any analysis. We then introduced null hypothesis significance testing (NHST) as a framework for evaluating whether observed patterns in data are likely to reflect real relationships in the population or could plausibly have occurred by chance. Throughout the chapter, the <span class="math inline">\(p\)</span>-value served as a tool for quantifying uncertainty, reminding us that statistical tests do not prove relationships but instead help us assess the strength of evidence against the null hypothesis.</p>
<p>Building on this framework, we explored several measures of association, each suited to different types of variables and research questions. The Chi-square test allowed us to evaluate relationships between categorical variables, Spearman’s rho helped us assess associations between ordinal variables, and rank-based tests such as the Mann–Whitney U and Kruskal–Wallis tests enabled comparisons of distributions across groups when outcomes were ordinal. Across all examples, emphasis was placed on considering direction, strength, statistical significance, and practical meaning.</p>
<p>It’s important to remember that statistical tools are part of an iterative research process that links theory, measurement, analysis, and interpretation. Thoughtful hypothesis formulation, appropriate test selection, and cautious interpretation are all essential for drawing meaningful conclusions about relationships and deciding which are worth including in our final report.</p>
</section>
<section id="reflection-questions" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="reflection-questions"><span class="header-section-number">6.6</span> Reflection Questions</h2>
<ol type="1">
<li><p><strong>Hypotheses translate research questions into testable claims.</strong> Why is it important to clearly identify independent and dependent variables before conducting a hypothesis test?</p></li>
<li><p><strong>Different statistical tests are suited to different types of variables.</strong> What problems can arise if a test designed for categorical variables is applied to ordinal or continuous data, or vice versa?</p></li>
<li><p><strong>Several examples in this chapter resulted in failing to reject the null hypothesis.</strong> Why is this outcome still informative, and how should non-significant findings be communicated in applied environmental research?</p></li>
<li><p><strong>Measures of association summarize relationships but not underlying processes.</strong> Why is contextual knowledge essential for translating statistical findings into meaningful insights for watershed management or policy decisions?</p></li>
</ol>
</section>
<section id="references" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="references"><span class="header-section-number">6.7</span> References</h2>
<div class="references">
<ul>
<li>Arthur, M. M. L., &amp; Clark, R. (2021). Social Data Analysis: Qualitative and Quantitative Approaches. Open Educational Resource.<a href="https://pressbooks.ric.edu/socialdataanalysis/" class="uri">https://pressbooks.ric.edu/socialdataanalysis/</a>.</li>
<li>Agresti, A. (2018). Statistical Methods for the Social Sciences (5th ed.). Pearson.</li>
<li>Conover, W. J. (1999). Practical Nonparametric Statistics (3rd ed.). Wiley.</li>
</ul>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter5.html" class="pagination-link" aria-label="Describing Survey Data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Describing Survey Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter7.html" class="pagination-link" aria-label="Research Writing">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Research Writing</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>